### PR TITLE
tests: Don't start DotcomWeb.Endpoint as a server in tests

### PR DESCRIPTION
**Pull request by joshlarson**
#### Summary of changes

Start `DotcomWeb.Endpoint` without the `server: true` flag in tests.

Starting `DotcomeWeb.Endpoint` with `server: true` causes the tests to fail if anything is already running on the port supplied (in this case `4002`). That conflicts with the docker config, which runs `dotcom-1` on the same port, so if you try to run `mix test` while the docker setup is running, they will reliably fail.

Completely removing `DotcomWeb.Endpoint` runs afoul of [one test][0], which has `localhost:4002` hard-coded in its assertion, which is why I didn't completely obliterate it the `DotcomWeb.Endpoint` invocation. Another option, which I'm open to, would be to remove the hard-coded `localhost:4002` from that test.

[0]: https://github.com/mbta/dotcom/blob/6ba2846bf84efcf545d42b51d08f3860d8ec9d64/test/cms/paragraph_test.exs#L327

---

#### General checks
* [x] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [x] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [x] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

#### New UI, or substantial UI changes
* [x] **Cross-browser compatibility** is less of an issue now that we're no longer supporting IE, but changes still need to work as expected in Safari, Chrome, and Firefox.
* [x] **Are interactive elements accessible?** This includes at minimum having [relevant keyboard interactions](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#keyboard-interaction) and [visible focus](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus), but can also include verification with screen reader testing.
* [x] **Other accessibility checks** such as sufficient [color constrast](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#color-contrast), or whether the layout holds up at 200% [zoom level](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus).

#### New endpoints, or non-trivial changes to current endpoints
* [x] **Have we load-tested** any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../load_tests/README.md)
* [x] **If this change involves routes,** does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?

### CODE REVIEW

**Comment by anthonyshull** [comment]
Which test checks that value? We can probably remove it too.

**Comment by joshlarson** [comment]
@anthonyshull https://github.com/mbta/dotcom/blob/6ba2846bf84efcf545d42b51d08f3860d8ec9d64/test/cms/paragraph_test.exs#L323-L328

**Review by thecristen — CHANGES_REQUESTED** [review]
Wow, had no idea about the test. I'm in favor of removing the hardcoded `localhost:4002` from the relevant test.

**Comment by anthonyshull** [comment]
There are a few tests that reference localhost:4002. Pretty sure they are just looking at URLs. Not sure they actually expect anything to be running. If it's just checking for a URL we can probably remove the localhost part and just use `=~`.

**Comment by joshlarson** [comment]
@anthonyshull @thecristen - I removed a bunch of hard-coded `localhost:4002`'s in [this commit](https://github.com/mbta/dotcom/pull/2180/commits/0b5329a1e35c4f9e6def9be671587a66b8cf057a)

**Review by anthonyshull — APPROVED** [review]

**Review by thecristen — APPROVED** [review]

**Pull request merged**
