### PR TITLE
Multistage docker builds / deploys via GitHub Actions

### PR DESCRIPTION
**Pull request by paulswartz**
#### Summary of changes
**Asana Ticket:** no ticket

- The fix for the React renderer was to copy the `dist/app.js` file out of the assets container and into the final stage container.
- `upload_assets.sh` was updated to pull the static files out with a `tar` command
- `deploy-dev-green.yml` is from the "Deploy to ElasticBeanstalk" workflow template, with the addition of the upload assets step.

Build: https://github.com/paulswartz/dotcom/actions/runs/925884220
Running on dev-green looks fine.

---

Before getting review, please check the following:

* [ ] Does frontend functionality render and work correctly in IE?
* [ ] Have we load-tested any new pages or internal API endpoints that will receive significant traffic?
* [ ] Are interactive elements accessible to screen readers?
* [ ] Have you checked for tech debt you can address in the area you're working in?
* [ ] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [ ] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Comment by ryan-mahoney** [comment]
@paulswartz this is excellent!

@alicia-mbta @hannahpurcell I looked at dev-green, and it looks good. Do you remember any of the specific pages that might have had issues when the previous ticket was merged? If so, can you verify that you are seeing what you would expect on dev-green?

**Review by alicia-mbta — APPROVED** [review]

**Comment by hannahpurcell** [comment]
Does it make sense that the CMS pieces of the site aren't connected on dev-green?  Is that an expected side-effect, or is that a problem?

**Comment by ryan-mahoney** [comment]
@paulswartz @hannahpurcell did we ever resolve the CMS verification issues?

**Comment by paulswartz** [comment]
@ryan-mahoney yes, the CMS was out of date but otherwise working correctly.

**Review by ryan-mahoney — APPROVED** [review]
Big Improvement!

**Comment by paulswartz** [comment]
Ignoring the failed Semaphore build.

**Pull request merged**
