### PR TITLE
Display monthly commuter pass for trip plans

### PR DESCRIPTION
**Pull request by arkadyan**
#### Summary of changes
**Asana Ticket:** [Fare Calculator Accordion | Recommended Passes](https://app.asana.com/0/555089885850811/1169236529454075)

Display monthly commuter pass for trip plans.

Include reduced pass where applicable.

Depends on https://github.com/mbta/dotcom/pull/499

---

Before getting review, please check the following:

* [x] Does frontend functionality render and work correctly in IE?
* [x] Have we load-tested any new pages or internal API endpoints that will receive significant traffic?
* [x] Are interactive elements accessible to screen readers?
* [x] Have you checked for tech debt you can address in the area you're working in?
* [x] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [x] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Comment by ingridpierre** [comment]
Weird breakpoints continue to torment - let's take the word "Commuter" out. "Monthly Passes" will suffice.
image

**Comment by ingridpierre** [comment]
For consistency, and to visually break up the subsections, the 1 col/SM/XS layout of the accordion should be indented the way that the fares in the blue header are. 

_Current:_

[indent] **Subheader in bold**
[indent] Fare: Cost
[indent] Fare: Cost

_Desired:_

**Subheader in bold**
[indent] Fare: Cost
[indent] Fare: Cost

In the example here, the subheaders **"Bus (Inner Express Bus)", "Subway", "Total...", "Inner Express"** should not be indented.
image

**Comment by arkadyan** [comment]
@ingridpierre I changed the wording to just, "Monthly Passes".

I also adjusted the indentation at small sizes. Is this in line with what you were looking for?

Screen Shot 2020-06-12 at 10 56 08

**Comment by ingridpierre** [comment]
Looks grrrreat! 👍

**Pull request merged**
