### PR TITLE
Animated bus

### PR DESCRIPTION
**Pull request by hannahpurcell**
#### Summary of changes
**Asana Ticket:** [Add updated animated bus image](https://app.asana.com/0/555089885850811/1201073069115355)

### CODE REVIEW

**Review by thecristen — CHANGES_REQUESTED** [review]
Let's add something, anything? to constrain the width so it's not so in our face?? 😳 

image

**Comment by thecristen** [comment]
I'm not sure how many of the Green Line -related tests rebasing this branch would fix, but it looks like there are plenty of error page-related tests to update as well!

* test/site_web/controllers/helpers_test.exs:21
* test/site_web/controllers/helpers_test.exs:386
* test/site_web/views/error_view_test.exs:14
* test/site_web/views/error_view_test.exs:19
* test/site_web/views/error_view_test.exs:24
* test/site_web/views/error_view_test.exs:40
* test/site_web/controllers/fare_controller_test.exs:29

**Comment by hannahpurcell** [comment]
🥲 we made it.  all tests updated.

**Review by thecristen — APPROVED** [review]
Thank you!

**Pull request merged**
