### PR TITLE
Add a script to assist with creating GitHub releases

### PR DESCRIPTION
**Pull request by arkadyan**
#### Summary of changes
**Asana Ticket:** [Determine the info from git to be able to print out everything you need to make a release manually](https://app.asana.com/0/385363666817452/1198965985597277/f)
which is the first step for [🔧 Use a script to automate GitHub releases](https://app.asana.com/0/385363666817452/1185680283158788/f)

Add a script to assist with creating GitHub releases

Currently, it asks you to confirm some defaults and generates everything
you'll need to create a release manually in your browser. For a next
phase, it would be nice if it used the GitHub API to create the release
for you. I want to get that going next, but this already provides substantial value during the deploy process so it seems like it's worth getting in right away.

Screen Shot 2020-10-28 at 18 44 22

---

Before getting review, please check the following:

* [x] Does frontend functionality render and work correctly in IE?
* [x] Have we load-tested any new pages or internal API endpoints that will receive significant traffic?
* [x] Are interactive elements accessible to screen readers?
* [x] Have you checked for tech debt you can address in the area you're working in?
* [x] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [x] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Comment by arkadyan** [comment]
@ianwestcott Feel free to chime in if you have any feedback on the utility or the python in general.

**Comment by ianwestcott** [comment]
@arkadyan was it a deliberate choice to avoid using external libraries like [GitPython](https://gitpython.readthedocs.io/en/stable/)? (Apologies if we discussed this already and I forgot)

**Comment by arkadyan** [comment]
@ianwestcott Nope! I didn't realize that existed (and I guess scripting this way for so long means I didn't think to look). Since this is working maybe I'll add what I have and then add another phase to replace it with that library.

**Comment by arkadyan** [comment]
Ticket for GitPython: https://app.asana.com/0/385363666817452/1198968561086741/f

**Comment by ianwestcott** [comment]
FWIW there's also a GitHub library you could use when the project progresses to that point: https://github.com/PyGithub/PyGithub

**Review by thecristen — COMMENTED** [review]
Should we have some config or something to specify which version(s?) of Git these scripts expect?

**Review by thecristen — APPROVED** [review]
This is really nifty!

**Comment by arkadyan** [comment]
@thecristen That's an interesting question about the git version. I think this is only using pretty basic features, so I wouldn't expect it to be very picky about the version. Let me know what you think, but my instinct would be to not worry about it until we come across a problem, and then [replace the implementation](https://app.asana.com/0/385363666817452/1198968561086741/f) soon anyway.

**Comment by thecristen** [comment]
@arkadyan Sounds good to me!

**Pull request merged**
