### PR TITLE
Define a RoutesApi behaviour

### PR DESCRIPTION
**Pull request by arkadyan**
#### Summary of changes
**Asana Ticket:** [Define a RoutesApi behaviour for V3Api.Routes](https://app.asana.com/0/1189396929591657/1189396929591660)

Define a RoutesApi behaviour

Mark V3Api.Routes as implementing this behaviour.

---

Before getting review, please check the following:

* [ ] Does frontend functionality render and work correctly in IE?
* [ ] Have we load-tested any new pages or internal API endpoints that will receive significant traffic?
* [ ] Are interactive elements accessible to screen readers?
* [ ] Have you checked for tech debt you can address in the area you're working in?
* [ ] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [ ] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Comment by alicia-mbta** [comment]
I think the `behaviour` approach is a good one. Any concerns, @cristen, @paulswartz?<br/>
If not, the work for this is already completed in this PR by @arkadyan 🙏

**Comment by paulswartz** [comment]
I think my comment the last time was whether we wanted the behavior to be about the `V3API.Routes` interface, or the `Routes.Repo` interface?

**Comment by thecristen** [comment]
This is a great question. I like the idea of doing this at the API level. But I'm trying to think about what it might look like if we extrapolate this pattern to all tests ... and wouldn't we need a similar behavior for the Routes.Repo interface anyway? 🤔

**Comment by thecristen** [comment]
Closing since we have https://github.com/mbta/dotcom/pull/761

**Pull request closed without merging**
