### PR TITLE
fix: Remove special cases for Franklin line

### PR DESCRIPTION
**Pull request by arkadyan**
#### Summary of changes

No ticket. I came across this issue while attempting to debug for https://github.com/mbta/dotcom/pull/1441.

fix: Remove special cases for Franklin line

This code is attempting to filter out shapes with names that don't exist any longer in the current schedule. Therefore, it wasn't actually doing anything at all beyond the base case.

---

#### General checks
* [x] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [x] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [x] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

Before and after screenshots showing there is no change:

prod0
Production direction 0

branch0
This branch direction 0

prod1
Production direction 1

branch1
This branch direction 1

### CODE REVIEW

**Comment by arkadyan** [comment]
@lund5000 and @thecristen calling you out just in case there's something about this I'm missing.

**Review by thecristen — APPROVED** [review]
Seems like a straightforward deletion to me.

**Comment by arkadyan** [comment]
@thecristen I added a couple of small and unrelated test fixes, if you could please take a quick final look. Thanks!

**Review by thecristen — APPROVED** [review]
Ah, clever fix. Thanks!!

**Pull request merged**
