### PR TITLE
Show real-time vehicles on new line diagram

### PR DESCRIPTION
**Pull request by digitalcora**
Visualizing Green Line bunching in real-time! 🚀

### CODE REVIEW

**Comment by ingridpierre** [comment]
For commuter rail only, can we add train #s to the tooltip? Looks like we do it on the timetable and the map, but not through this version of the line diagram. See:
image
image
**CURRENT:**
image

**DESIRED:**
image

**Comment by ingridpierre** [comment]
Also, can we left align the tooltip label? Or have some general tooltip rules that update the text alignment based on where the arrow is pointing?  (e.g.: if arrow is left or right, text-align left. If arrow is top or bottom, text-align center.)

**Comment by digitalcora** [comment]
> For commuter rail only, can we add train #s to the tooltip?

Done.

> Also, can we left align the tooltip label here?

Mmmmmaybe. This turned out to be surprisingly non-trivial so I'll get back to you.

**Comment by ingridpierre** [comment]
IE 11, Win 10 - no map or line diagram rendered apart from the header. 😨 
image

**Comment by digitalcora** [comment]
@ingridpierre Cristen noticed this as well, I'm working on a fix at the moment

**Pull request merged**
