### PR TITLE
chore: add Lynn & Winthrop ferry fare info

### PR DESCRIPTION
**Pull request by thecristen**
#### Summary of changes

**Asana Ticket:** [Ferry Fares Page | Add fare cards for Lynn and Winthrop](https://app.asana.com/0/385363666817452/1204827964401105/f)

Gonna deploy this to dev-green and leave this as a draft while I test if this change works with the (sandbox-mbta) CMS. (edit: done, it works!)

I mostly followed the code changes used when we added the fares for the East Boston ferry in #1411 

The one missed opportunity for optimization here - East Boston, Lynn, and Winthrop have the same one-way fares, so potentially that code could be more streamlined. But I know one of them is increasing in price at the end of summer, and E Boston has reduced fare that might not be the same as the others... so I didn't want to consolidate those if they're not meant to be identical.

---

#### General checks
* [x] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [x] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [ ] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

### CODE REVIEW

**Comment by i0sea** [comment]
Looking at dev green Winthrop is missing at the moment

**Comment by thecristen** [comment]
> Looking at dev green Winthrop is missing at the moment

@i0sea Sorry, I'd only added the Lynn one. Added both now :)

**Review by i0sea — CHANGES_REQUESTED** [review]
Looks good on mobile. Desktop styling doesn't match mocks. Thinking its a grid issue, screenshot below 
Screen Shot 2023-06-26 at 2 20 49 PM

**Review by i0sea — COMMENTED** [review]
Also does the order need to match the mocks?

**Comment by thecristen** [comment]
@i0sea That's for hasty example to demonstrate it functions... the content experts will take care of placement and positioning once this is deployed and `{{fare:ferry_winthrop}}` and `{{fare:ferry_lynn}}` become available for them to use.

**Review by i0sea — APPROVED** [review]
Alright, lgtm

**Pull request merged**
