### PR TITLE
Make subject field required

### PR DESCRIPTION
**Pull request by alicia-mbta**
#### Summary of changes
**Asana Ticket:** [☎️ Make subject field required](https://app.asana.com/0/555089885850811/1188547161220081)

Do not allow submission if field is not filled:<br/>
image

### CODE REVIEW

**Comment by thecristen** [comment]
I'm not sure this needs design review as it doesn't incorporate the design proposal (https://app.asana.com/0/385363666817452/1199530274677101/f) yet... but otherwise it does the job 👍

**Review by thecristen — APPROVED** [review]

**Review by paulswartz — COMMENTED** [review]
should there also be server-side validation that subject is present?

**Review by thecristen — COMMENTED** [review]
I think the subject might also need to be included in the setupValidation() function in support-form.js, otherwise looks like the rest of the pieces are all there.

**Review by thecristen — APPROVED** [review]
👍

**Pull request merged**
