### PR TITLE
feat(DepartureTimes): Show certain formats based of mode type

### PR DESCRIPTION
**Pull request by kotva006**
#### Summary of changes
Cancelled and Delayed formatting should only happen on the Commuter Rail, Ferry, and Bus.
For subway if it is cancelled or delayed only show the next time.

**Asana Ticket:** [Departure Cards Cancelled and Delayed Times](https://app.asana.com/0/home/1201123880594717/1204554128687100)

---

#### General checks
* [ ] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [ ] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [ ] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

#### New UI, or substantial UI changes
* [ ] **Cross-browser compatibility** is less of an issue now that we're no longer supporting IE, but changes still need to work as expected in Safari, Chrome, and Firefox.
* [ ] **Are interactive elements accessible?** This includes at minimum having [relevant keyboard interactions](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#keyboard-interaction) and [visible focus](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus), but can also include verification with screen reader testing.
* [ ] **Other accessibility checks** such as sufficient [color constrast](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#color-contrast), or whether the layout holds up at 200% [zoom level](https://thinkdobecreate.com/articles/4-required-tests-before-shipping-new-features/#visible-focus).

#### New endpoints, or non-trivial changes to current endpoints
* [ ] **Have we load-tested** any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../apps/site/load_tests/README.md)
* [ ] **If this change involves routes,** does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204554128687100

### CODE REVIEW

**Review by thecristen — CHANGES_REQUESTED** [review]
I hard-coded some cancellations and the results look reasonable, and the code changes all make sense. But I don't see here any logic for this one acceptance criteria:

- For bus, cancelled & delayed trips should only be shown if the departure time is >= 1 hour away.

**Comment by kotva006** [comment]
I am starting to feel like the goal posts of these requirements are constantly moving and becoming impossible to nail down

**Comment by thecristen** [comment]
Was just citing a bullet from the linked ticket.

**Review by thecristen — APPROVED** [review]
It's really neat seeing the new bits of logic build upon the prior changes rather elegantly, given the complexity. Let's go!

**Pull request merged**
