### PR TITLE
Fixing various broken line diagram issues

### PR DESCRIPTION
**Pull request by thecristen**
#### Summary of changes
**Asana Ticket:** [Line Diagram | Shuttles should not break the line](https://app.asana.com/0/385363666817452/1199904083874239/f)

There are actually two different problems being tackled here. Going to deploy on dev green to make it easier to check many routes with the green dev API data.

### First commit

CR-Kingston was broken because the line diagram decided that _South Station - Kingston_ and _South Station - Plymouth via Kingston_ were two separate branches. The latter route pattern covers all of the same stops the former one does, so we choose to show only _South Station - Plymouth via Kingston_ on the line diagram.

The chosen fix adds a new function, `overall_branch`, that takes lists of stops and finds the list whose stops cover all of the stops on all other lists. E.g. one branch to rule them all. If an "overall branch" is found, then use that for the line diagram instead of trying to piece together multiple branches.

### Second commit

CR-Fitchburg was broken because of new rail replacement bus shuttle service for portions of the route. These additional route patterns were creating extra "branches" for the line diagram. Both the normal rail version and the shuttle bus version are marked with same route pattern typicality value of 1.

This could have been automatically fixed by the `overall_branch` logic to select the normal rail route pattern, however this bus shuttle includes an extra stop that _isn't_ present in the rail version of the route. 

Ideally there would be a way to write some logic that inspects the rail_replacement_bus route pattern stops for stops that are not normally served by the particular rail line that that bus is replacing... but as far as I can tell there isn't.

So the fix chosen for this issue is more targeted, looking at this particular shuttle (Alewife-Littleton) and excluding the one known extra stop (Alewife) from consideration as part of the `overall_branch` logic.

---

Before getting review, please check the following:

* [ ] Does frontend functionality render and work correctly in IE?
* [ ] Have we load-tested any new pages or internal API endpoints that will receive significant traffic?
* [ ] Are interactive elements accessible to screen readers?
* [x] Have you checked for tech debt you can address in the area you're working in?
* [x] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [x] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Comment by paulswartz** [comment]
> The chosen fix adds a new function, `overall_branch`, that takes lists of stops and finds the list whose stops cover all of the stops on all other lists. E.g. one branch to rule them all. If an "overall branch" is found, then use that for the line diagram instead of trying to piece together multiple branches.

FYI: this will break again when Kingston goes back to having trips ending at both Kingston and Plymouth. I don't know when this will be, but something to keep an eye on.

**Review by alicia-mbta — APPROVED** [review]
I really like your approach.<br/>
Taking to account [Paul's comment](https://github.com/mbta/dotcom/pull/806#issuecomment-781561343), my only comment/question is whether `maybe_use_overarching_branch` should have a more Kingston-related name since that seems to be the only current exception (although you built the function to be generic)?<br/>
That way perhaps it'll be easier to identify if these changes need to be readjusted when Kingston goes back to having trips ending at both Kingston and Plymouth?

**Comment by hannahpurcell** [comment]
If a shuttle is involved in the Fitchburg line, shouldn't there be a barber pole in the line diagram?  Or is the barber pole part of another situation?

**Comment by thecristen** [comment]
@hannahpurcell Conceptually I think it _should_ have a barberpole pattern in the line diagram, but the data for _that_ depends on alerts existing on the appropriate stops. SO that's a different thing. :/

@alicia-mbta  We discussed the Kingston/Plymouth route's trips on Slack and based on the route patterns involved I don't think it's will be an issue .... also the function is helping with the Fitchburg route too, so I'm going to keep the name as is. :)

**Review by hannahpurcell — APPROVED** [review]

**Pull request merged**
