### PR TITLE
fix: Use the secrets format to retrieve the token

### PR DESCRIPTION
**Pull request by arkadyan**
#### Summary of changes
No ticket

This is a shot in the dark, not sure if it will actually do anything to
fix the failing GitHub action or not, but found this syntax in some
[GitHub documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api)
and it seemed like it wouldn't hurt to try it.

---

Before getting review, please check the following:

* [ ] Does frontend functionality render and work correctly in IE?
* [ ] Have we load-tested any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../apps/site/load_tests/README.md)
* [ ] Are interactive elements accessible to screen readers?
* [ ] Have you checked for tech debt you can address in the area you're working in?
* [ ] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [ ] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Comment by thecristen** [comment]
AFAIK there's no way to test that without having this workflow code in the `master` branch, right? 🤔

**Comment by arkadyan** [comment]
@thecristen I was hoping it might work to try deploying this branch at a time when GH action deploys of other branches were failing. But I have no idea if that would work (and maybe it's not even possible?)

**Comment by thecristen** [comment]
I'm like 90% deploying this will use the old version of this work flow but it's totally worth a try!

**Comment by arkadyan** [comment]
@thecristen Ah yeah, I suspect you are probably right. I'll leave it up to you if (and when) you want to try merging it and seeing if the next deployment goes any better. We can always back it out later.

**Comment by thecristen** [comment]
I don't think we can assess if this PR helps or not because the failure happens beforehand - I think it's a formatting error around getting/passing the URLs -- see https://github.com/mbta/dotcom/runs/7999667770?check_suite_focus=true

**Comment by thecristen** [comment]
Decided to try these out in https://github.com/mbta/dotcom/commit/707d0b627cb75900cbb6e20f184432302c6b6374, we'll see how it goes! Thanks.

**Pull request closed without merging**
