### PR TITLE
Add scripts to build and push to ECR

### PR DESCRIPTION
**Pull request by phildarnowsky**
#### Summary of changes
**Asana Ticket:** [🔧 Add ECR build/push scripts to dotcom repo](https://app.asana.com/0/555089885850811/1164017148038358)

See https://app.asana.com/0/385363666817452/1161415406861110/f for details

### CODE REVIEW

**Comment by phildarnowsky** [comment]
@ianwestcott are you able to comment on Cora's question #1 above?

**Comment by ianwestcott** [comment]
This is indeed meant to replace the use of `build.sh` within the context of the Semaphore build (see https://semaphoreci.com/mbta/dotcom/servers/dev/edit). That said, it looks like there's some logic in `build.sh` specific to this project, so maybe it does make sense to merge the two, or incorporate one into the other? Also I can't speak to whether this change would render `build.sh` obsolete for all potential use cases related to dotcom work.

**Comment by digitalcora** [comment]
I don't believe any of the current team have ever touched `build.sh` — if it's not for the Semaphore build, then it's not for anything.

**Comment by paulswartz** [comment]
The API kept `build.sh` the step which creates a .zip file to upload to ElasticBeanstalk, and created a separate `build_push.sh` which does the ECR steps: https://github.com/mbta/api/blob/master/build.sh and https://github.com/mbta/api/blob/master/semaphore/build_push.sh

**Comment by ianwestcott** [comment]
@phildarnowsky is this waiting on anything else, other than a resolution on the discussion of whether to keep/refactor/eliminate `build.sh`? I want to make sure I'm not a blocker here.

**Comment by phildarnowsky** [comment]
Closing this PR for the sake of neatness, put the task in the backlog for re-evaluation.

**Pull request closed without merging**
