### PR TITLE
Add new routes with crowding data

### PR DESCRIPTION
**Pull request by arkadyan**
#### Summary of changes
**Asana Ticket:** [9 new routes with crowding data](https://app.asana.com/0/555089885850811/1181885620584410)

Add new routes with crowding data

---

Before getting review, please check the following:

* [x] Does frontend functionality render and work correctly in IE?
* [x] Have we load-tested any new pages or internal API endpoints that will receive significant traffic?
* [x] Are interactive elements accessible to screen readers?
* [x] Have you checked for tech debt you can address in the area you're working in?
* [x] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [x] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Comment by paulswartz** [comment]
What is this used for? Downstream applications shouldn't need to care about which routes have been approved for crowding information.

**Comment by arkadyan** [comment]
@paulswartz We want to shift the design in some cases based on whether a route you are looking at might have crowding data. E.g., If you are looking at a route with crowding data, we will display a column in a table for a crowding icon. If a specific vehicle isn't serving up data we can simply leave that column blank, but the column is still there. On the other hand, on a route without crowding data that will never show that icon, it is preferable to remove the column altogether.

**Comment by arkadyan** [comment]
Holding for 6/26

**Comment by paulswartz** [comment]
> @paulswartz We want to shift the design in some cases based on whether a route you are looking at might have crowding data. E.g., If you are looking at a route with crowding data, we will display a column in a table for a crowding icon. If a specific vehicle isn't serving up data we can simply leave that column blank, but the column is still there. On the other hand, on a route without crowding data that will never show that icon, it is preferable to remove the column altogether.

Can you base it on whether there's any crowding data for the vehicles being displayed, rather than the route? That's similar to what Skate is doing.

**Comment by arkadyan** [comment]
@paulswartz That's an interesting idea that I can't remember if we've thought about. I'll make a ticket for the team to consider.

**Pull request merged**
