### PR TITLE
Customer Support Form improvements

### PR DESCRIPTION
**Pull request by thecristen**
This PR serves as a final check, there should be no surprises here. ;)

#### Summary of changes
**Asana Ticket:** [New CS Form Feature Complete + Live](https://app.asana.com/0/1139110203450767/1194612062768617/f)

All the changes to the customer support form! Including but not limited to:

* Reworked layout
* Backend support for new fields
* New fields added on front end, including a few interdependent fields 
* Reversed logic for requiring contact info on the form

---

Before getting review, please check the following:

* [x] Does frontend functionality render and work correctly in IE?
* [x] Have we load-tested any new pages or internal API endpoints that will receive significant traffic?
* [ ] Are interactive elements accessible to screen readers?
* [x] Have you checked for tech debt you can address in the area you're working in?
* [x] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [ ] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Comment by alicia-mbta** [comment]
I think that the test that's breaking (added in #660) is because the parameters that I specified might be only valid for the day of. With the shuttles and other changes that the Green Line is going through, I wonder if it makes more sense to remove that test and try another approach?

**Comment by thecristen** [comment]
I can confirm it works* in IE! 😄 

*Well, the photo _preview_ does not work in IE. But it turns out it didn't work in IE to begin with. 🥴 
Anyway, I'm not sure if/how this affects the uploaded photo being submitted.

**Comment by alicia-mbta** [comment]
> I can confirm it works* in IE! 😄
> 
> *Well, the photo _preview_ does not work in IE. But it turns out it didn't work in IE to begin with. 🥴
> Anyway, I'm not sure if/how this affects the uploaded photo being submitted.

Would it be worth to submit a couple more tickets using IE (to see what's received by HEAT) and create a new ticket to investigate the photo preview in IE? not sure how important this is since you mentioned it doesn't even work in the current customer support form.

**Comment by thecristen** [comment]
@alicia-mbta  definitely let's create a ticket for this existing IE bug.

**Comment by aararomi** [comment]
lgtm

**Comment by alicia-mbta** [comment]
> definitely let's create a ticket for this existing IE bug.

For reference, here is the [Asana ticket](https://app.asana.com/0/385363666817452/1199514633650926) for this.

**Review by paulswartz — APPROVED** [review]
:cake:

**Pull request merged**
