### PR TITLE
Meeting info in sidebar

### PR DESCRIPTION
**Pull request by hannahpurcell**
#### Summary of changes
**Asana Ticket:** [Add Meeting info section to right-hand rail](https://app.asana.com/0/555089885850811/1199945602717945)

Meeting info details moved to sidebar.  The location doesn't match the design perfectly, because the "Location" field on events includes the floor number.  If that was a separate field, then I could tweak the design a little more precisely.

---

* [ ] Does frontend functionality render and work correctly in IE?
* [ ] Are interactive elements accessible to screen readers?

### CODE REVIEW

**Review by alicia-mbta — CHANGES_REQUESTED** [review]
The redesign looks good to me. However, on mobile the blue block disappears? 😨 
Let me know if it's a glitch on my end.

**Comment by hannahpurcell** [comment]
> The redesign looks good to me. However, on mobile the blue block disappears? 😨
> Let me know if it's a glitch on my end.

Ope!  Nope, not a glitch.  Big oversight, lol 😓

**Comment by thecristen** [comment]
What you're seeing is probably the funkiness of how CMS paragraphs work here: IIRC, custom paragraphs get rendered into the template twice - once in the main area (often in a user-specified area of the page) and once in the sidebar - and each is hidden or shown based on media query - this is how sometimes we can have a different order of content on mobile, and how the right side content can appear interwoven into the main content.

**Review by thecristen — APPROVED** [review]
This LGTM, with the same note that @alicia-mbta noted. 

TBH I wonder if that noted issue might resolve itself once the overall page layout is fixed to have the same width as the navbar (screenshot from Safari below with issue that shows on prod right now where the content + sidebar seems dramatically narrower than the page)

image

**Comment by alicia-mbta** [comment]
Oh ok good point. I guess we can keep an eye on it.

**Review by alicia-mbta — APPROVED** [review]

**Comment by hannahpurcell** [comment]
Ohhoo weird!  Thanks for noticing and discussing!  Do we have a ticket for fixing that bigger layout issue?

**Pull request merged**
