### PR TITLE
Set up dev preview page for Trip Planner WIP

### PR DESCRIPTION
**Pull request by thecristen**
#### Summary of changes

**Asana Ticket:** [Set up dev preview page for Trip Planner WIP](https://app.asana.com/0/385363666817452/1207763166362686/f)

Instead of hacking at the current trip planner incrementally, we'll use a fresh view to start implementing the desired UX/UI changes. This page will be shared across the team for iterative feedback while we explore new ways of grouping and displaying itineraries.

> [!Tip]
>
> Visit `/preview/trip-planner` using the basic auth username/password (this is in 1Password under "Dotcom Basic Auth" in the Website Dev vault for prod/dev/dev-blue/dev-green, or locally with `BASIC_AUTH_USERNAME` and `BASIC_AUTH_PASSWORD` environment variables)

image

### CODE REVIEW

**Review by bklebe — COMMENTED** [review]
Is this deployed anywhere in staging or dev so we can verify the basic functionality works as we believe it should?

**Comment by thecristen** [comment]
nope, I can deploy it to dev-blue though

**Comment by anthonyshull** [comment]
> Is this deployed anywhere in staging or dev so we can verify the basic functionality works as we believe it should?

You can just run it locally.

**Comment by bklebe** [comment]
> > Is this deployed anywhere in staging or dev so we can verify the basic functionality works as we believe it should?
> 
> You can just run it locally.

I could, but I'm more confident in the similarity of dev and prod than prod and my workstation :)

**Review by bklebe — APPROVED** [review]

**Comment by bklebe** [comment]
Excellent, was able to check that the page is working on dev. Thanks so much!

**Pull request merged**
