### PR TITLE
feat(ENVRC): Update the template to have a placeholder for AWS creden…

### PR DESCRIPTION
**Pull request by kotva006**
…tials

#### Summary of changes
Add the AWS env variable placeholder to the template file

### CODE REVIEW

**Comment by paulswartz** [comment]
Should basic running of the Dotcom application require AWS credentials?

**Comment by kotva006** [comment]
@paulswartz It looks like when Cristen added the [bus alerts storage](https://github.com/mbta/dotcom/commit/377cbd4dd1fa812fc65be7bbd78af6adc7286a4b) it made it required for startup

**Comment by paulswartz** [comment]
Yes, but should that be the case? Could it be optional?

**Comment by kotva006** [comment]
@paulswartz It probably shouldn't be required.  The service should fail gracefully, log a message, and allow the system to keep running.
There are other services besides the bus alerts that use the AWS credentials (Search).  Also most of the env variables in that template file aren't required to get the server up and running.
Figures adding a placeholder for those variables informs people that there are AWS requirements for some parts of the website.  It has also become a pain point for a couple uses.  Having it standardized should hopefully make it less of an issue in the future for people spinning up the site, and enabling features.

**Review by i0sea — APPROVED** [review]
🚀

**Pull request merged**
