### PR TITLE
feat(Feedback.Mailer): respect size/count file limit

### PR DESCRIPTION
**Pull request by thecristen**
#### Summary of changes

**Related Asana Tickets:** There's not really a ticket for addressing file requirements specifically, but this is related to the ongoing work in support of [Customer Support | Feedback Form Won't Submit with Attachments](https://app.asana.com/0/385363666817452/1203879636893641/f) and [Customer Support | Image attachments sometimes producing error](https://app.asana.com/0/385363666817452/1200247859025319/f)

I've learned that IRIS, the incident reporting system that ingests the information we intake via our Customer Support form over at `/customer-support`, has a few limitations:

* No more than 6 file attachments per ticket
* Attached files must be no larger than 2 MB

So this PR adjusts our logic to support that. I added new test cases and test images to help verify this functionality.

---

#### General checks
* [x] **Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?** This is a good practice that can facilitate easier reviews.
* [x] **Testing.** Do the changes include relevant passing updates to tests? This includes updating screenshots. Preferably tests are run locally to verify that there are no test failures created by these changes, before opening a PR.
* [x] **Tech debt.** Have you checked for tech debt you can address in the area you're working in? This can be a good time to address small issues, or create Asana tickets for larger issues.

### CODE REVIEW

**Comment by thecristen** [comment]
Deployed on dev-blue. If you submit the form with attachments I can log into the dev version of the incident reporting system and verify the files made it there. I think I finally got this working! 😩 

image

**Comment by i0sea** [comment]
just submitted an image larger than 2MB. Is it compressed to a smaller size in the incident reporting system? @thecristen

**Comment by thecristen** [comment]
@i0sea The images aren't compressed (and large images are discarded). That's a wonderful idea I hadn't even considered!

**Review by i0sea — APPROVED** [review]
lgtm. I think it'd be nice to have a followup ticket to have some sort of error popup when there are to many attachments/large files rather than just dropping the excess and submitting.

**Comment by thecristen** [comment]
@i0sea Thanks for your tests, I can see the logs of them in Splunk ([link](https://mbta.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22dotcom-dev-blue-application%22%20Support&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-3h%40h&latest=now&sid=1677089360.44173))

I also found some errors... looks like I still have more debugging to do 😟 
image

**Comment by thecristen** [comment]
@i0sea Your testing exposed that AWS SES (which we use to send the email) wasn't handling filenames with spaces in it! I've fixed that now. Going to roll with it and try it on dev next!

**Pull request merged**
