### PR TITLE
Internet Explorer warning

### PR DESCRIPTION
**Pull request by alicia-mbta**
#### Summary of changes
**Asana Ticket:** [Implement IE browser warning](https://app.asana.com/0/555089885850811/1200138787176597)

Show a warning suggesting to switch to a different browser other than Internet Explorer:

ie

### CODE REVIEW

**Review by hannahpurcell — CHANGES_REQUESTED** [review]
Ooooo, it's been a bit since I've reviewed a React file!  

It looks like the modal doesn't persist across the site (at least not when I test it with BrowserStack, so maybe it's a BS problem [hehe]).  Whatever page I land on initially will show the modal, but if I navigate to another page, the modal disappears.

**Comment by alicia-mbta** [comment]
Did you click on the 'Ok, got it!' button? Once you click on it, it should not appear again for the rest of your session.
From the specs, this was so the overlay would remain unobtrusive when collapsed (so you can still use the page).

**Comment by hannahpurcell** [comment]
No, didn't click the "got it" button.  I just clicked a link to another page (schedules), and the warning goes away.  I've tested with a few other links, and the warning doesn't persist for me.  Does it stay for you?

**Comment by thecristen** [comment]
Hm, hadn't thought about how to persist the unanswered warning when clicking around the website. Maybe we can track whether the IE message was dismissed by using a cookie - see `SiteWeb.Plugs.Cookies` for how we show recently visited routes on the home page.

**Review by hannahpurcell — APPROVED** [review]
Looks and works great for me!

**Comment by thecristen** [comment]
Going to merge this for you 🥰

**Pull request merged**
