### PR TITLE
Add service dropdown to schedule finder

### PR DESCRIPTION
**Pull request by katehedgpeth**
#### Summary of changes
**Asana Ticket:** [⏱Schedules | Finder Tool - Schedule picker](https://app.asana.com/0/555089885850811/1121929590554557)

Adds a service dropdown to the schedule finder. Selecting a service does not fetch schedules yet.

<br>
Assigned to: @meagonqz // @ingridpierre

### CODE REVIEW

**Comment by meagonqz** [comment]
@ingridpierre This could use a product review before I continue work on it. 

What do you think of the date ranges? The data we receive is "start_date" and "end_date", I'm not sure how programmatically we'd future proof date ranges to correlate to ratings. We could hardcode it since we do have usually have to update Backstop for our tests every rating but I'd worry that might change in the future and be overlooked?

**Comment by ingridpierre** [comment]
Looks like what we ended up getting data-wise isn't making this dropdown look as I expected.

There are a couple things I'd like to see if this is what we have to work with.

1. Add two optgroups:
CURRENT SCHEDULES
OTHER SCHEDULES

2. Within those optgroups, we should be able to use today's date to know what ranges we belong to and list those separately. 
3. For current schedules show end date, for other schedules, show start date. 
4. We should have a concept of which schedule should be selected automatically, right? Currently the default for me shows a sunday schedule, but we should know the day of the week and show the right one. If today were a holiday I would expect to see the holiday show up as the default selection.

Ideally this cleans it up a bit and we can show something more like:

**CURRENT SCHEDULES**
 - Weekday (Monday - Friday), ends June 5
- Saturday Schedule, ends June 8
- Sunday Schedule, ends June 10

**OTHER SCHEDULES**
- Weekday (Monday - Friday), starts June 5
- Saturday Schedule, starts June 8
- Sunday Schedule, starts June 10

**Comment by meagonqz** [comment]
@ingridpierre I structured the opt groups and changed the language. 

I changed the default option to always be "weekday typical". I think this since this ticket is blocking other work, we should merge this as is and look to do a smarter default selection later.

**Comment by meagonqz** [comment]
@ingridpierre I added better default selection logic.

**Comment by meagonqz** [comment]
@ryan-mahoney @ingridpierre this is ready for review

**Comment by ingridpierre** [comment]
@meagonqz I've updated my comment above with the new wording to accommodate for friday-only schedules. Hopefully it makes sense given what we're getting.

**Comment by meagonqz** [comment]
@ingridpierre This is ready with the change in your comment.

**Comment by ingridpierre** [comment]
@meagonqz lgtm! 👍 Thanks for spending the extra time on this one, I feel pretty good about the changes helping us move forward on schedules.

**Pull request merged**
