### PR TITLE
Account for empty list of stops

### PR DESCRIPTION
**Pull request by alicia-mbta**
#### Summary of changes
**Asana Ticket:** [🐞 Elixir.FunctionClauseError: no function clause matching in Stops.RouteStops.branch/1](https://app.asana.com/0/555089885850811/1191546277787129)

I'm not sure if this is a valid solution, hence the draft PR. If it is, I will create the corresponding test for it.

### CODE REVIEW

**Comment by paulswartz** [comment]
I'm a little confused here. The URL that triggered the error was https://www.mbta.com/schedules/map_api?shape_id=813_0006&id=Green&direction_id=0 which makes sense: `813_0006` is a shape_id: https://api-v3.mbta.com/shapes/813_0006

However, it looks like the API requests being made are treating it as a route pattern ID: 
```

api-response-1 | V3Api.get_json_response url="/route_patterns/813_0006" params={} status=404 content_length=133 duration=3.031 request_id=2p6fh87ekl03tced1c310oq1
-- | --
api-response-3 | V3Api.get_json_response url="/route_patterns/813_0006" params={} status=304 content_length=0 duration=2.443 request_id=2p6fh87ekl03tced1c310oq1
api-response-5 | V3Api.get_json_response url="/route_patterns/813_0006" params={} status=304 content_length=0 duration=3.2 request_id=2p6fh87ekl03tced1c310oq1
api-response-7 | V3Api.get_json_response url="/route_patterns/813_0006" params={} status=304 content_length=0 duration=2.95 request_id=2p6fh87ekl03tced1c310oq1
api-response-error-2 | V3Api.get_json_response url="/route_patterns/813_0006" params={} response={"errors":[{"code":"not_found","source":{"parameter":"id"},"status":"404","title":"Resource Not Found"}],"jsonapi":{"version":"1.0"}}
api-response-error-4 | V3Api.get_json_response url="/route_patterns/813_0006" params={} response={"errors":[{"code":"not_found","source":{"parameter":"id"},"status":"404","title":"Resource Not Found"}],"jsonapi":{"version":"1.0"}}
api-response-error-6 | V3Api.get_json_response url="/route_patterns/813_0006" params={} response={"errors":[{"code":"not_found","source":{"parameter":"id"},"status":"404","title":"Resource Not Found"}],"jsonapi":{"version":"1.0"}}
api-response-error-8 | V3Api.get_json_response url="/route_patterns/813_0006" params={} response={"errors":[{"code":"not_found","source":{"parameter":"id"},"status":"404","title":"Resource Not Found"}],"jsonapi":{"version":"1.0"}}
```

Can you see why the shape ID is getting treated as a route pattern? That might be underlying the issue.

**Comment by alicia-mbta** [comment]
You're right, I hadn't noticed that.
I think that calling`LineHelpers.get_branch_route_stops` giving it the `shape_id` when it's expecting a `route_pattern_id` makes the wrong calls (as you mentioned). If we don't specify that parameter at all, we get a `200 OK`. But since I'm still not sure if this is the right approach, perhaps I'm still missing something.

**Comment by paulswartz** [comment]
This looks like it works! Can we add a test for this?

**Comment by thecristen** [comment]
Can we also make sure other routes aren't adversely affected by this change? I'd look at some of the "weird" routes described in Ingrid's useful places to QA doc https://www.notion.so/Useful-Places-To-Test-in-QA-3a3c609634f145f787251785411b0445

**Comment by thecristen** [comment]
Slightly related,  sharing here as an FYI: I have a work in progress branch that intersects with this - in which I renamed the `shape_id` param as` route_pattern_id` since I had this same observation 😅 . 

Anyway, like I said - I'm hoping this change doesn't adversely affect other routes.

**Comment by alicia-mbta** [comment]
I think this change only affects map data but perhaps it goes beyond that and I'm not seeing it.
In any case, if your branch already had a fix for this plus more changes, do you think it makes sense to close this then?

**Comment by thecristen** [comment]
I think it's fine to make this change, as long as it doesn't adversely change the shapes shown on maps (has this been checked?).

**Comment by alicia-mbta** [comment]
As far as I could see, everything looked ok to me. I will be merging at some point today if no other concerns.

**Comment by alicia-mbta** [comment]
Can this be approved if there are no concerns? 😅

**Review by paulswartz — APPROVED** [review]
🍰

**Pull request merged**
