### PR TITLE
Project page filters

### PR DESCRIPTION
**Pull request by phildarnowsky**
#### Summary of changes
**Asana Ticket:** [🗂️ Project Index |  Filter - Mode filters](https://app.asana.com/0/555089885850811/1136817875129090)

Added mode-filter buttons that determine which projects and project updates are shown on this page, by mode.

<br>
Assigned to: @meagonqz

### CODE REVIEW

**Comment by phildarnowsky** [comment]
@meagonqz this should address all your feedback, I expect all tests to pass except for one of the Elixir tests I fixed this morning.

**Comment by ingridpierre** [comment]
An adjustment we'd like to the logic here would be to include more projects in any remaining feature/banner slots, ordered by most recently updated. Currently we only include projects labeled as sticky, but when a filter is active we'd like to see sticky + most recent in the Featured Projects.

**Comment by ingridpierre** [comment]
In the XS breakpoint it seems that the banner element disappears.

**Comment by ingridpierre** [comment]
In XS, the filter buttons should use 100% of the width (2x2 stretched to fit) , I think the fixed size here is creating some undesirable gaps for mobile devices:

image

**Comment by ingridpierre** [comment]
Looks like the banner color isn't coming through here, should be purple I imagine, but also we should have a default color (primary blue) when there's no mode or line tagged (to see this I filtered by CR projects). 
image

**Comment by ingridpierre** [comment]
Also not seeing banner elements show up at all in XS breakpoint.

**Comment by ryan-mahoney** [comment]
@ingridpierre thanks for reviewing, looking into those issues now

**Comment by ryan-mahoney** [comment]
@phildarnowsky I spoke to Ingrid about this yesterday in Slack.

The color issue was resolved. The only remaining issue is the first item should appear in a banner style even at XS breakpoint.

**Comment by phildarnowsky** [comment]
@ingridpierre The version currently on dev-green should remedy the XS-banner problem.

**Comment by ingridpierre** [comment]
@phildarnowsky 👍 looks fabulous!

**Pull request merged**
