### PR TITLE
Add ellipsis to long headsign names

### PR DESCRIPTION
**Pull request by ryan-mahoney**
#### Summary of changes
**Asana Ticket:** [⏱ Schedules | Add ellipsis to long headsign names](https://app.asana.com/0/477545582537986/1124353435273956/f)

- This change has no effect to most headsigns, but now longer ones will not wrap.
- removed zone tag for all modes except CR

#### Checklist
- [x] New functions have typespecs, changed functions' typespecs were updated
- [x] New modules and functions have documentation, changed modules/functions' documentation was updated
- [x] Tests were added or updated to cover changes
- [x] All tests pass on localhost:
  - [x] `npm test` (includes mix test, JS tests, and Backstop)
  - [x] `npm run dialyzer`
  - [x] `pronto run -c origin/master`

<br>
Assigned to: @amaisano

### CODE REVIEW

**Comment by ingridpierre** [comment]
image
Seeing some predicted times wrapping  at the smallest breakpoint (320w).

**Comment by ryan-mahoney** [comment]
@ingridpierre please take another look

**Comment by ingridpierre** [comment]
image
Still seeing the previous issue, am I missing new changes here? 

Agree with Adamo above about not needing to trim characters until in his example, we should only trim if and when the headsign + time prediction start to wrap to 2 lines.

But the repeated headsigns he mentioned are expected behavior.

**Comment by ryan-mahoney** [comment]
@ingridpierre okay, ready for another look :D

**Comment by ingridpierre** [comment]
@ryan-mahoney thanks! lgtm now 👍

**Pull request merged**
