### PR TITLE
Expand and scroll to selected month

### PR DESCRIPTION
**Pull request by alicia-mbta**
#### Summary of changes
**Asana Ticket:** [Clicking on the nav link on the left should expand the corresponding month](https://app.asana.com/0/555089885850811/1200312808499748)

A different approach in an attempt to achieve the desired behavior. Related to #940.

### CODE REVIEW

**Comment by hannahpurcell** [comment]
The first 5 or so events of the month are visible, but you can't scroll to the end of the event list for a month.  Here's a gif of trying to scroll to the end of April, but the events are covered by the May header

Jun-10-2021 08-30-53

**Comment by alicia-mbta** [comment]
Ouch that's not good...reverting.

**Review by hannahpurcell — APPROVED** [review]
Oh nice!  Simple and sweet.  I think the note on the asana ticket said this task would go back into the backlog, but this looks 100% finished to me, right?

**Review by thecristen — APPROVED** [review]
LGTM!

**Pull request merged**
