### PR TITLE
Update location of CrossBrowserTesting AuthKey

### PR DESCRIPTION
**Pull request by phildarnowsky**
They moved it.

### CODE REVIEW

**Comment by digitalcora** [comment]
As the person who wrote this just a couple weeks back (in #429), when I saw this I thought I had the worst timing ever, for CBT to remove this UI right after... but looking at it today, it's still there for me? Maybe I'm in a parallel universe 😄

I guess the Account page is a more reliable place to find the auth key after all. Shame it requires navigating away from the main test dashboard.

Screen Shot 2020-03-23 at 10 33 53 AM

**Comment by digitalcora** [comment]
As the person who wrote this just a couple weeks back (in #429), when I saw this I thought I had the worst timing ever, for CBT to remove this UI right after... but looking at it today, it's still there for me? Maybe I'm in a parallel universe 😄

I guess the Account page is a more reliable place to find the auth key after all. Shame it requires navigating away from the main test dashboard.

Screen Shot 2020-03-23 at 10 33 53 AM

**Comment by beeuhtricks** [comment]
The A/B test strikes again? Here's mine, for comparison: 
Screen Shot 2020-03-23 at 11 35 57 AM

**Comment by beeuhtricks** [comment]
AHA! 

> You can download the correct version of the standalone binary for your system by logging into your CBT account **(on any browser other than Chrome)** and clicking along the top where it says “Local Connection”.


Emphasis mine.

**Comment by digitalcora** [comment]
Ah, I see. With Chrome they want you to install their Chrome Extension, so they direct you away from the manual command-line workflow. I forgot that as a Firefox user I _do_ live in a parallel universe!

**Comment by phildarnowsky** [comment]
@digitalcora @beeuhtricks in any case, I see I have a little revision to do here.

**Comment by digitalcora** [comment]
@phildarnowsky I think it's good as-is; the Account page should reliably have the auth key on it, no matter what browser you're using.

**Comment by beeuhtricks** [comment]
Yeah, and I would just rather not use the Chrome extension anyways.

**Comment by phildarnowsky** [comment]
@beeuhtricks @digitalcora could one of you please approve this puppy when you have a minute?

**Pull request merged**
