### PR TITLE
Add status to more-projects table

### PR DESCRIPTION
**Pull request by phildarnowsky**
#### Summary of changes
**Asana Ticket:** [Add status to project index more-projects table](https://app.asana.com/0/555089885850811/1135411616097675)

Added the "Status" field to the table, against the day when we have a significant number of them filled in.

<br>
Assigned to: @ryan-mahoney

### CODE REVIEW

**Comment by aayesha** [comment]
I've added status to the majority of projects, so this should look OK once live. There are a few that are intentionally blank and a few that we still need to confirm, but most are filled in.

**Comment by phildarnowsky** [comment]
@aayesha Once this is approved by dev and design, I'd like to check this against dev-green just to be sure.

**Comment by amaisano** [comment]
FYI dev and test were just synced in the CMS envs today.

**Comment by phildarnowsky** [comment]
@liana this is ready for another look on https://green.dev.mbtace.com/projects at your convenience.

**Pull request merged**
