### PR TITLE
Sentry Bugfix:  Function Clause Error in CMS.Page.Basic.from_api

### PR DESCRIPTION
**Pull request by hannahpurcell**
#### Summary of changes
**Asana Ticket:** [Elixir.FunctionClauseError: no function clause matching in CMS.Partial.MenuLinks.from_api/1](https://app.asana.com/0/555089885850811/1199555004763320)

If a CMS page has the attribute field_sidebar_menu, the value should either be populated or an empty array.  But there was a continual issue with the page http://mbta.com/sustainability/community-programs/, in which the field_sidebar_menu value was getting parsed as [nil] (an array with just the value nil.)

In the solution, I was able to adjust the function match for this situation.  Still, I don't know how to determine why that value was getting parsed as [nil] instead of nil or [], since the above link redirects to http://mbta.com/sustainability/, a different page.

### CODE REVIEW

**Comment by thecristen** [comment]
@amaisano I'm curious if you have any thoughts about this bug!

**Comment by amaisano** [comment]
Let me check the source data. I think that menu field is totally deprecated at this point anyway.

**Comment by amaisano** [comment]
FYI you can access the original page that caused the error by using this link: https://www.mbta.com/sustainability/community-programs-OLD?preview=&vid=19288&nid=3186

**Comment by amaisano** [comment]
The JSON response to elixir for that was https://live-mbta.pantheonsite.io/cms/revisions/3186?vid=19288&_format=json, which indeed shows a null inside an array. This is an error state in the CMS for the field value. The problematic page has been archived, and the [current revision](https://live-mbta.pantheonsite.io/cms/revisions/3186?vid=51654&_format=json) of it is returning a `[]` value.

There is a good chance that the menu object this field was referencing was deleted some time ago. When this happens, the CMS puts a NULL value in but keeps the field placeholder. This is what I think happened.

**Comment by amaisano** [comment]
The JSON response to elixir at the time the page was live indeed showed a null inside an array. This is an error state in the CMS for the field value. The problematic page has been archived, and the current revision of it is returning a [] value.

There is a good chance that the menu object this field was referencing was deleted some time ago. When this happens, the CMS puts a NULL value in but keeps the field placeholder. This is what I think happened.

**Comment by amaisano** [comment]
This is a risk for any entity reference field I think, so we may want to create an abstracted CMS field struct to handle this more generally...

**Comment by alicia-mbta** [comment]
If that field is deprecated, it would be good to remove it entirely.
And create a CMS-related ticket to create that field @amaisano suggested?
Hannah's fix looks good to me. For now, anyway 🙂

**Review by alicia-mbta — APPROVED** [review]

**Review by thecristen — APPROVED** [review]
I'm going to agree and say this is good to go! Good talk.

**Pull request merged**
