### PR TITLE
☎️ Replace Full Name field with First Name and Last Name fields

### PR DESCRIPTION
**Pull request by thecristen**
#### Summary of changes
**Asana Ticket:** [☎️ Replace Full Name field with First Name and Last Name fields](https://app.asana.com/0/385363666817452/1188547161220117/f)

The page seems to break on form submit so there's an extra commit meant to address that as well...

---

Before getting review, please check the following:

* [x] Does frontend functionality render and work correctly in IE?
* [x] Have we load-tested any new pages or internal API endpoints that will receive significant traffic?
* [x] Are interactive elements accessible to screen readers?
* [x] Have you checked for tech debt you can address in the area you're working in?
* [x] If this change involves routes, does it work correctly with pertinent "unusual" routes such as the combined Green Line, Silver Line, Foxboro commuter rail, and single-direction bus routes like the 170?
* [x] Are the changes organized into self-contained commits with descriptive and well-formatted commit messages?

### CODE REVIEW

**Review by alicia-mbta — APPROVED** [review]
Left a small comment but nothing major.
The other question I have is whether this branch should be merged into the feature branch instead of `master`?

**Comment by thecristen** [comment]
> Left a small comment but nothing major.
> The other question I have is whether this branch should be merged into the feature branch instead of `master`?

You're totally right; I updated the target branch to be the feature branch, thanks for catching!

**Comment by ingridpierre** [comment]
This appears to function fine when I'm in the form, but I'm yet to see any confirmation emails populate from test submissions. Am I missing something needed here?

**Comment by thecristen** [comment]
@ingridpierre with regards to no email response, [buried in the docs](https://github.com/mbta/dotcom/tree/master/apps/feedback#development-logging):

> In development, the application is configured to print the contents of the email to the log instead of sending an actual email. This is logged at the `info` log level, but the default log level is set to warn. Add `LOGGER_LEVEL=info` to your .env file to see the feedback emails in your logs.

So when developing locally you wouldn't get an email, but you can see the recorded information logged in your terminal window if you have the logger level variable set as specified above. Sorry I hadn't mentioned this when posting this PR :/

**Pull request merged**
